### ISSUE TITLE
Need a way to disable line number from the results window

### ISSUE THREAD

**Issue by ronakg** [pechorin/any-jump.vim#21]
See the screenshot. I want to disable line numbers from the results window.

<img width="1102" alt="Screen Shot 2020-03-05 at 4 32 45 PM" src="https://user-images.githubusercontent.com/1058322/76038669-0e6e4300-5eff-11ea-96ad-4e9339180996.png">

**Comment by crivotz** [comment]
Same issue, already tried with `et g:any_jump_list_numbers = 0` but without success

**Comment by pechorin** [comment]
Thanks for report, will fix it very soon.

**Comment by pechorin** [comment]
Fixed in https://github.com/pechorin/any-jump.vim/commit/bda6d753e553aa54c0f130e7ab0b55ae9dc2692e

**Comment by pechorin** [comment]
Please update plugins :)

**Comment by ronakg** [comment]
Thanks for the line number fix. The sign column is still showing up. Can you disable that as well for the results window?
